package core


import "path/filepath"
import "os"
import "encoding/json"


// see https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes
type Theme struct {
	ImagesZipUri string `json:"imagesZipUri"`
	ImageFilename string `json:"imageFilename"`
	ImageCredits string `json:"imageCredits"`
	DayHighlight int `json:"dayHighlight"`
	NightHighlight int `json:"nightHighlight"`
	DayImageList []int `json:"dayImageList"`
	SunriseImageList []int `json:"sunriseImageList"`
	SunsetImageList []int `json:"sunsetImageList"`
	NightImageList []int `json:"nightImageList"`
}





func WriteTheme(workDir string, steps int) {
	sunsetLen := steps - 2
	if sunsetLen < 0 {
		sunsetLen = 0
	}

	sunsetIndex := make([]int, sunsetLen)
	for idx := 0; idx < sunsetLen; idx++ {
		sunsetIndex[idx] = idx+2
	}

	sunriseIndex := make([]int, sunsetLen)
	for idx := 0; idx < sunsetLen; idx++ {
		sunriseIndex[idx] = sunsetIndex[sunsetLen - idx - 1]
	}


	// generate json
	theme := Theme { ImagesZipUri: "", 
					 ImageFilename: "image_*.png",
					 ImageCredits: "generated by DynDesktopBuilder",
					 DayHighlight: 1,
					 NightHighlight: steps,
					 DayImageList: []int { 1 },
					 SunriseImageList: sunriseIndex,
					 SunsetImageList: sunsetIndex,
					 NightImageList: []int { steps } }

	outFile := filepath.Join(workDir, "theme.json")
	outputFile, err := os.Create(outFile)
	CheckError(err, "failed to write json file")
	defer outputFile.Close()	

	encoder := json.NewEncoder(outputFile)
	encoder.SetIndent("", " ")
	err = encoder.Encode(theme)
	CheckError(err, "failed to encode to json")
}
